export const countryList = [
  { country: 'United States of America', countryCode: 'US' },
  { country: 'India', countryCode: 'IN' },
  { country: 'Africa', countryCode: 'AFRICA' },
  { country: 'Algeria', countryCode: 'DZ' },
  { country: 'Argentina', countryCode: 'AR' },
  { country: 'Asia', countryCode: 'ASIA' },
  { country: 'Australia', countryCode: 'AU' },
  { country: 'Austria', countryCode: 'AT' },
  { country: 'Belarus', countryCode: 'BY' },
  { country: 'Belgium', countryCode: 'BE' },
  { country: 'Brazil', countryCode: 'BR' },
  { country: 'Canada', countryCode: 'CA' },
  { country: 'Cayman Islands', countryCode: 'KY' },
  { country: 'Chile', countryCode: 'CL' },
  { country: 'China', countryCode: 'CN' },
  { country: 'Colombia', countryCode: 'CO' },
  { country: "Cote D'Ivoire (Ivory Coast)", countryCode: 'CI' },
  { country: 'Croatia (Hrvatska)', countryCode: 'HR' },
  { country: 'Cyprus', countryCode: 'CY' },
  { country: 'Denmark', countryCode: 'DK' },
  { country: 'Ecuador', countryCode: 'EC' },
  { country: 'Egypt', countryCode: 'EG' },
  { country: 'Estonia', countryCode: 'EE' },
  { country: 'Ethiopia', countryCode: 'ET' },
  { country: 'Europe', countryCode: 'EUROPE' },
  { country: 'Finland', countryCode: 'FI' },
  { country: 'France', countryCode: 'FR' },
  { country: 'Georgia', countryCode: 'GE' },
  { country: 'Germany', countryCode: 'DE' },
  { country: 'Ghana', countryCode: 'GH' },
  { country: 'Hong Kong S.A.R.', countryCode: 'HK' },
  { country: 'Indonesia', countryCode: 'ID' },
  { country: 'Ireland', countryCode: 'IE' },
  { country: 'Israel', countryCode: 'IL' },
  { country: 'Italy', countryCode: 'IT' },
  { country: 'Kenya', countryCode: 'KE' },
  { country: 'Latam', countryCode: 'LATAM' },
  { country: 'Lithuania', countryCode: 'LT' },
  { country: 'Malaysia', countryCode: 'MY' },
  { country: 'Malta', countryCode: 'MT' },
  { country: 'Mexico', countryCode: 'MX' },
  { country: 'Middle east', countryCode: 'MIDDLE_EAST' },
  { country: 'Morocco', countryCode: 'MA' },
  { country: 'Netherlands', countryCode: 'NL' },
  { country: 'Nigeria', countryCode: 'NG' },
  { country: 'North America', countryCode: 'NORTH_AMERICA' },
  { country: 'Norway', countryCode: 'NO' },
  { country: 'Pakistan', countryCode: 'PK' },
  { country: 'Panama', countryCode: 'PA' },
  { country: 'Peru', countryCode: 'PE' },
  { country: 'Philippines', countryCode: 'PH' },
  { country: 'Poland', countryCode: 'PL' },
  { country: 'Romania', countryCode: 'RO' },
  { country: 'Singapore', countryCode: 'SG' },
  { country: 'Slovenia', countryCode: 'SI' },
  { country: 'South Africa', countryCode: 'ZA' },
  { country: 'South Korea', countryCode: 'KR' },
  { country: 'Southeast Asia', countryCode: 'SOUTHE_ASIA' },
  { country: 'Spain', countryCode: 'ES' },
  { country: 'Sweden', countryCode: 'SE' },
  { country: 'Switzerland', countryCode: 'CH' },
  { country: 'Tanzania', countryCode: 'TZ' },
  { country: 'United Arab Emirates', countryCode: 'AE' },
  { country: 'United Kingdom', countryCode: 'GB' },
  { country: 'Ukraine', countryCode: 'UA' },
  { country: 'Venezuela', countryCode: 'VE' },
  { country: 'Vietnam', countryCode: 'VN' },
  { country: 'Zambia', countryCode: 'ZM' },
];
export const quranList = [
  { name: 'Docs', format: 'pdf' },
  { name: 'Book', format: 'pdf' },
];

export const platformList = [
  { name: 'Social Media', platform: 'online' },
  { name: 'TV', platform: 'tv' },
  { name: 'Banner', platform: 'physical' },
  { name: 'other', platform: 'other' },
];

export const salutationList = [
  { key: 'Mr.', value: 'male' },
  { key: 'Mrs.', value: 'female' },
  { key: 'Ms.', value: 'female' },
];
